vich_uploader:
    db_driver: orm

    mappings:
        blog_images:
            uri_prefix: '%app.path.featured_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.featured_images%'
